### PR TITLE
fix: resolve assert_stmt and config_entry correctly

### LINKED ISSUE #921: [Enhancement] Symbol definition for the string interpolation in the assert statement
## Enhancement

```python
a = "123"
assert True, "${a}456" # symbol "a" is not found.
```

### PR DESCRIPTION
**Pull request by NeverRaR**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 

fix #921 
#### 2. What is the scope of this PR (e.g. component or file name):

/kclvm/sema
#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [x] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

**Comment by Peefy** [comment]
@CodiumAI-Agent /review
@CodiumAI-Agent /improve

File: kclvm/sema/src/advanced_resolver/mod.rs [hunk 1]
```diff
@@ -396,47 +396,12 @@ mod tests {
                 ],
             ),
             (
-                "src/advanced_resolver/test_data/pkg/pkg.k"
+                "src/advanced_resolver/test_data/import_test/d.k"
```
Comment (Peefy) [inline kclvm/sema/src/advanced_resolver/mod.rs:399]: Considering improve code according to the [CodiumAI-Agent](https://github.com/CodiumAI-Agent) comments and fix CI unit tests

**Review by Peefy — APPROVED** [review]
LGTM
