### PR TITLE
fix: fix `net.is_IP_in_CIDR` with IPv6

### LINKED ISSUE #1905: net.is_IP_in_CIDR does not work for IPv6
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
import net
x = net.is_IP_in_CIDR('2001:db8::1', "2001:db8::/64")
```

### 2. What did you expect to see? (Required)

`true`

### 3. What did you see instead (Required)

`false`

### 4. What is your KCL components version? (Required)

Whatever KCL Playground is running.

### PR DESCRIPTION
**Pull request by He1pa**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y fix #1905 

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [x] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

**Review by zong-zhe — APPROVED** [review]
LGTM

**Comment by zong-zhe** [comment]
cc @johngmyers 😄

File: kclvm/runtime/src/net/mod.rs [hunk 1]
```diff
@@ -509,35 +510,72 @@ pub extern "C-unwind" fn kclvm_net_is_IP_in_CIDR(
...
     }
+}
+
+fn _parse_cidr(cidr: &str) -> Option<(IpAddr, Option<u32>)> {
+    let parts: Vec<&str> = cidr.split('/').collect();
+    if parts.len() != 2 {
+        return None;
+    }
+    let ip = IpAddr::from_str(parts[0]).ok()?;
+    let mask_bits = parts[1].parse::<u32>().ok();
```
Comment (johngmyers) [inline kclvm/runtime/src/net/mod.rs:556]: This incorrectly succeeds if `ip` has bits set beyond `mask_bits`. For example, `10.11.0.0/8`.

File: kclvm/runtime/src/net/mod.rs [hunk 2]
```diff
@@ -509,35 +510,72 @@ pub extern "C-unwind" fn kclvm_net_is_IP_in_CIDR(
...
+    Some((ip, mask_bits))
+}
 
-    panic!("is_IP_in_CIDR() missing 2 required positional arguments: 'ip' and 'cidr'");
+fn _parse_ip(ip: &str) -> Result<IpAddr, ()> {
+    IpAddr::from_str(ip).map_err(|_| ())
+}
+
+fn _check_ipv4_cidr(ip: Ipv4Addr, cidr_ip: Ipv4Addr, mask_bits: u32) -> bool {
```
Comment (johngmyers) [inline kclvm/runtime/src/net/mod.rs:564]: Why not use the `cidr` crate? I was just working on reimplementing `net.parse_cidr` using it.

File: kclvm/runtime/src/net/mod.rs [hunk 3]
```diff
@@ -509,35 +510,72 @@ pub extern "C-unwind" fn kclvm_net_is_IP_in_CIDR(
...
+    let mask = !((1u32 << (32 - mask_bits)) - 1);
```
Comment (johngmyers) [inline kclvm/runtime/src/net/mod.rs:565]: Does this not overflow for `0.0.0.0/0`?

File: test/grammar/builtins/net/cidr/main.k [hunk 4]
```diff
@@ -5,3 +5,4 @@ cidr1 = net.hosts_in_CIDR("192.168.1.0/24")
 cidr2 = net.subnets_from_CIDR("192.168.1.0/24")
 cidr3 = net.is_IP_in_CIDR("192.168.1.1", "192.168.1.0/24")
 cidr4 = net.is_IP_in_CIDR("192.168.0.1", "192.168.1.0/24")
+cidr5 = net.is_IP_in_CIDR('2001:db8::1', "2001:db8::/64")
```
Comment (johngmyers) [inline test/grammar/builtins/net/cidr/main.k:8]: There should be a LOT more tests:
* First in CIDR
* Last in CIDR
* One before first in CIDR
* One after last in CIDR
* `0.0.0.0/0` and `::/0`
* IPv4 in `::/0`
* IPv4 in IPv6 CIDR and vice versa
* Invalid CIDRs
* Invalid IPs
* IPv4 /32 and IPv6 /128

**Review by johngmyers — CHANGES_REQUESTED** [review]
