### PR TITLE
fix: Defend against  non-KCL files

### LINKED ISSUE #795: [Bug][LSP]AnalysisDatabase not found error after rename file
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create file a.k
rename to aa.k

### 3. What did you see instead (Required)

lQLPJwl2vf3Ja2TNAYLNCvKwBHV6_uT30xUFI4afWECsAA_2802_386

### PR DESCRIPTION
**Pull request by He1pa**
When the client renames a file, if the file suffix is changed, some requests will also be sent. However, it is considered not a valid kcl file during compilation, which will cause lsp panic.

#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y fix #795  

#### 2. What is the scope of this PR (e.g. component or file name):
tools/lsp

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):
When the client renames a file, if the file suffix is changed, some requests will also be sent. However, it is considered not a valid kcl file during compilation, which will cause lsp panic.
- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [x] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

File: kclvm/tools/src/LSP/src/request.rs [hunk 1]
```diff
@@ -128,7 +147,16 @@ pub(crate) fn handle_goto_definition(
 ) -> anyhow::Result<Option<lsp_types::GotoDefinitionResponse>> {
     let file = file_path_from_url(&params.text_document_position_params.text_document.uri)?;
     let path = from_lsp::abs_path(&params.text_document_position_params.text_document.uri)?;
-    let db = snapshot.get_db(&path.into())?;
+    let db = match snapshot.get_db(&path.clone().into())? {
```
Comment (Peefy) [inline kclvm/tools/src/LSP/src/request.rs:150]: Consider adding KCL file filters on VFS.

File: kclvm/tools/src/LSP/src/request.rs [hunk 2]
```diff
@@ -61,13 +63,30 @@ impl LanguageServerState {
 }
 
 impl LanguageServerSnapshot {
-    pub(crate) fn get_db(&self, path: &VfsPath) -> anyhow::Result<&AnalysisDatabase> {
+    // defend against non-kcl files
+    pub(crate) fn get_db(&self, path: &VfsPath) -> anyhow::Result<Option<&AnalysisDatabase>> {
```
Comment (Peefy) [inline kclvm/tools/src/LSP/src/request.rs:67]: Consider adding KCL file filters on VFS. That is to say, we can add a series of file filtering lists instead of just the hardcode `.k` suffix. Because KCL VFS needs to consider support for `kcl.mod`, `.json`, `.yaml` and `.kcl` files, etc.

File: kclvm/tools/src/LSP/src/request.rs [hunk 3]
```diff
@@ -145,7 +173,16 @@ pub(crate) fn handle_reference(
 ) -> anyhow::Result<Option<Vec<Location>>> {
     let file = file_path_from_url(&params.text_document_position.text_document.uri)?;
     let path = from_lsp::abs_path(&params.text_document_position.text_document.uri)?;
-    let db = snapshot.get_db(&path.clone().into())?;
+    let db = match snapshot.get_db(&path.clone().into())? {
+        Some(db) => db,
+        None => {
+            log_message(
```
Comment (Peefy) [inline kclvm/tools/src/LSP/src/request.rs:179]: Too many duplicate codes, please refer to the comments above about the VFS filter.

File: kclvm/tools/src/LSP/src/request.rs (hunk 2 above)
Comment (He1pa) [reply kclvm/tools/src/LSP/src/request.rs:67]: why we need to support `kcl.mod` `.json` `.yaml` and `.kcl` files in lsp vfs？

File: kclvm/tools/src/LSP/src/request.rs (hunk 1 above)
Comment (He1pa) [reply kclvm/tools/src/LSP/src/request.rs:150]: VFS only saves the mapping between FileId and sourcecode. When the file is changed, the sourcecode is compiled and the result is saved in the db. If it is not a valid kcl file, compilation fails and the corresponding compilation result will not be saved in the db. Therefore, if the request target is not a valid file, it will not be queried in the db. This problem has nothing to do with vfs or db, I think it should be filtered when processing requests

File: kclvm/tools/src/LSP/src/request.rs (hunk 2 above)
Comment (Peefy) [reply kclvm/tools/src/LSP/src/request.rs]: > why we need to support `kcl.mod` `.json` `.yaml` and `.kcl` files in lsp vfs？

KCL not only focuses on changes and compilation of KCL files themselves, but also includes analysis of changes in kcl. mod files, highlighting, and more. For widely used JSON, YAML and other data files in the ecosystem, we may consider using KCL for verification and displaying information on JSON, YAML and other files. Supplementary, this is a long-term consideration, and currently only the possibility of expansion can be retained.

**Review by Peefy — APPROVED** [review]
LGTM
