### PR TITLE
fix: add type annotation check during type checking in assignment

### LINKED ISSUE #746: [Bug] Type infer error for variable with the type annotation
## Enhancement

```python
lambda {
    containers = []
    if True:
        containers = []
    images: [str] = [c.image for c in containers]
}
```

image

For the var `images` in the above code, its right type annotation should be `[str]` instead of `any`

### PR DESCRIPTION
**Pull request by zong-zhe**
Signed-off-by: zongz <zongzhe1024@163.com>

#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 

Fixes #746 

#### 2. What is the scope of this PR (e.g. component or file name):

add type annotation check during type checking in assignment.

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [x] Unit test
- [x] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

File: kclvm/sema/src/resolver/node.rs [hunk 1]
```diff
@@ -185,6 +185,51 @@ impl<'ctx> MutSelfTypedResultWalker<'ctx> for Resolver<'ctx> {
...
                         );
                     }
+                    // If the assign statement has a type annotation like: `a: str = "test_str"`,
+                } else if assign_stmt.type_annotation.is_some() {
+                    // Get the type annotation.
+                    if let Some(ty_annotation) = &assign_stmt.ty {
+                        let annotation_ty = self
+                            .parse_ty_with_scope(&ty_annotation.node, ty_annotation.get_span_pos());
+                        // Set the type annotation as the target type.
+                        self.set_type_to_scope(name, annotation_ty.clone(), target.get_span_pos());
```
Comment (Peefy) [inline kclvm/sema/src/resolver/node.rs:195]: Split these logic to a smaller function.

Comment (zong-zhe) [reply kclvm/sema/src/resolver/node.rs]: fixed

**Review by Peefy — APPROVED** [review]
LGTM

**Review by i-zhen — COMMENTED** [review]
LGTM
