### PR TITLE
lfx pre test lsp quick fix

### LINKED ISSUE #1020: [LFX PreTest] PreTest for LSP quick fix
Provide quick fix with LSP for this case.
image

What you need to do:
1. Find the place where this error is generated in the kcl compiler(~/kclvm/sema/src/resolver/scope.rs  lookup_type_from_scope() and set_type_to_scope()) and fill in `suggested_replacement` in the structure representing the error. In this case it would be `Some("aaa")`
2. Convert KCL's Diagnostic to LSP's Diagnostic. Most of the work is already done, but you need to convert `suggested_replacement` into the `data` field.
```
pub struct Diagnostic {
    /// The range at which the message applies.
    pub range: Range,
   ...
    ///  A data entry field that is preserved between a `textDocument/publishDiagnostics`
    /// notification and `textDocument/codeAction` request.
    pub data: Option<serde_json::Value>,
}
```
3. handle the `CodeActionRequest` and provide a quick fix response. you can ref this pr: https://github.com/kcl-lang/kcl/pull/652. This is a very simple demo that fix warning about useless import. It replaces the useless import stmt with an empty string. But you need to get the `new_text` from RequestParam(The IDE will return the `data` generated in the previous step as a parameter)
4. Install KCL extension within VSCode and build lsp binary locally, add the `kcl-language-server` to PATH
5. After completing above, you can see a button like this in the IDE (VSCode). Click the button and the IDE will fix the incorrect code (aa->aaa)
image

You can fork this repository and develop in your own repository. After completion, you can contact me via email or slack. Of course, if you have any questions during this process, you can also contact me

### PR DESCRIPTION
**Pull request by shashank-iitbhu**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 

Close #1020 

#### 2. What is the scope of this PR (e.g. component or file name):

Adding LSP quick fix

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

https://github.com/kcl-lang/kcl/assets/134289475/4cc71209-b007-44f4-904e-ac3a40b7d140

- Extending the Diagnostic Structure ```pub data: Option<serde_json::Value>```, excluded data from hash calculation due to its json type
- Used function overloading in rust to modify ```add_compile_error``` to work when data field is None
- Filled the data in ```lookup_type_from_scope()``` and ```set_type_to_scope()```
- modified ```conver_code_to_kcl_diag_id``` for CompileError
- modified ```quick_fix``` to replace new_text with suggested_replacement
- finally, extended ```kcl_diag_to_lsp_diags``` to convert data field of KCL diagnostics to data field of LSP diagnostics.

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

File: kclvm/error/src/diagnostic.rs [hunk 1]
```diff
@@ -5,11 +5,23 @@ use std::hash::Hash;
 use crate::{ErrorKind, WarningKind};
 
 /// Diagnostic structure.
-#[derive(Clone, Debug, PartialEq, Eq, Hash)]
+#[derive(Clone, Debug, PartialEq, Eq)]
 pub struct Diagnostic {
     pub level: Level,
     pub messages: Vec<Message>,
     pub code: Option<DiagnosticId>,
+    pub data: Option<serde_json::Value>,
```
Comment (He1pa) [inline kclvm/error/src/diagnostic.rs:13]: you don’t need to define the data field in kcl’s diag. It is duplicated with suggested_replacement. As I explained in the step 2, the data field should be in the diag of lsp, not the diag of kcl. You can look up the function, kcl_diag_to_lsp_diags. this function convert KCL Diagnostic to LSP Diagnostics. you can see the data in result is always None. you should completed in here

Comment (shashank-iitbhu) [reply kclvm/error/src/diagnostic.rs]: Oh right, storing the data field in KCL diagnostics is redundant. Fixed this in latest commit, and made the relevant changes in the code to utilize ```suggested_replacement``` field for conversion of KCL Diagnostic to LSP Diagnostics.

**Comment by shashank-iitbhu** [comment]
Hey @He1pa , I have added test for the `ComplileError` Quick fix which i added before.
Now all the tests are passing. For this, I have added a compile error in `kclvm/tools/src/LSP/src/test_data/diagnostics.k` for this.

File: kclvm/tools/src/LSP/src/quick_fix.rs [hunk 2]
```diff
@@ -1,17 +1,42 @@
...
     let mut code_actions: Vec<lsp_types::CodeActionOrCommand> = vec![];
     for diag in diags {
         if let Some(code) = &diag.code {
             if let Some(id) = conver_code_to_kcl_diag_id(code) {
                 match id {
-                    DiagnosticId::Error(_) => continue,
+                    DiagnosticId::Error(error) => match error {
+                        ErrorKind::CompileError => {
+                            let replacement_text = extract_suggested_replacement(&diag.data)
+                                .unwrap_or_else(|| "".to_string());
```
Comment (He1pa) [inline kclvm/tools/src/LSP/src/quick_fix.rs:18]: if suggested resplacement is None, do nothing (just continue) instead of using an empty string.

File: kclvm/tools/src/LSP/src/quick_fix.rs [hunk 3]
```diff
@@ -1,17 +1,42 @@
...
+                            let mut changes = HashMap::new();
+                            changes.insert(
+                                uri.clone(),
+                                vec![TextEdit {
+                                    range: diag.range,
+                                    new_text: replacement_text,
+                                }],
+                            );
+                            code_actions.push(CodeActionOrCommand::CodeAction(CodeAction {
+                                title: ErrorKind::CompileError.name(),
```
Comment (He1pa) [inline kclvm/tools/src/LSP/src/quick_fix.rs:28]: image
The title is the part the user sees and should show how to fix it. For example, this is the tip given by rust-analyzer

File: kclvm/error/src/lib.rs [hunk 4]
```diff
@@ -126,14 +126,24 @@ impl Handler {
...
         let diag = Diagnostic::new_with_code(
             Level::Error,
             msg,
             None,
             range,
             Some(DiagnosticId::Error(E2L23.kind)),
-            None,
+            suggestions,
         );
+        // println!("{:?}",suggestions.clone());
```
Comment (He1pa) [inline kclvm/error/src/lib.rs:146]: remove

Comment (shashank-iitbhu) [reply kclvm/error/src/lib.rs]: removed.

File: kclvm/error/src/diagnostic.rs [hunk 5]
```diff
@@ -106,16 +106,16 @@ impl Diagnostic {
         note: Option<&str>,
         range: Range,
         code: Option<DiagnosticId>,
-        suggested_replacement: Option<String>,
+        suggestions: Option<Vec<String>>,
```
Comment (Peefy) [inline kclvm/error/src/diagnostic.rs:109]: s/`suggestions: Option<Vec<String>>`/`suggestions: Vec<String>`

File: kclvm/error/src/diagnostic.rs [hunk 6]
```diff
@@ -106,16 +106,16 @@ impl Diagnostic {
...
         Diagnostic {
             level,
             messages: vec![Message {
                 range,
                 style: Style::LineAndColumn,
                 message: message.to_string(),
-                note: note.map(|s| s.to_string()),
-                suggested_replacement,
+                note: note.map(String::from),
+                suggested_replacement: suggestions.and_then(|v| v.into_iter().next()),
```
Comment (Peefy) [inline kclvm/error/src/diagnostic.rs:118]: I think the suggested_replacement should be the `Vec<String>` type.

File: kclvm/tools/src/LSP/src/quick_fix.rs (hunk 3 above)
Comment (shashank-iitbhu) [reply kclvm/tools/src/LSP/src/quick_fix.rs]: In the latest commit, I have provided a formatted string to the `title`:
Screenshot 2024-02-19 at 5 01 52 PM

Is this the way to go with this?
<br>
The rust-analyzer also provides a tip along with a clickable link to the file like this:

Screenshot 2024-02-19 at 5 06 59 PM

Do we need something like this also? If yes, how to proceed?

File: kclvm/tools/src/LSP/src/quick_fix.rs (hunk 2 above)
Comment (shashank-iitbhu) [reply kclvm/tools/src/LSP/src/quick_fix.rs]: done.

File: kclvm/error/src/diagnostic.rs (hunk 5 above)
Comment (shashank-iitbhu) [reply kclvm/error/src/diagnostic.rs:109]: This will remain ```suggestions: Option<Vec<String>>```.

**Review by Peefy — APPROVED** [review]
Good Job! LGTM!
