### PR TITLE
fix: fix performance regression on resolver::parse_doc_string

### LINKED ISSUE #576: [Bug]  Resover doc parser performance problem
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)
image

Each fragment at the top of the figure represents a call to this function.
This function takes an estimated 60-70% of the time. After removing this function, the resolver time dropped from 70ms to 14ms

### PR DESCRIPTION
**Pull request by He1pa**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y

Closes #576 

#### 2. What is the scope of this PR (e.g. component or file name):
sema/resolver/doc.rs

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):
Use pcre2 to replace std::Reegex

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [x] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [x] Manual test (add detailed scripts or steps below)
- [ ] Other
 Manual test sema/resolver/tests::test_resolve_schema_doc and got 10-20 times enhance on method `strip_quotes`

Before
image

After:
image

### CODE REVIEW

File: kclvm/sema/src/resolver/doc.rs [hunk 1]
```diff
@@ -1,21 +1,28 @@
...
+    if let Ok(Some(mat)) = RE.find(original.as_bytes()) {
+        let content = str::from_utf8(&original.as_bytes()[mat.start() + 3..mat.end() - 3])
+            .unwrap()
+            .to_owned();
+        *original = content;
+        
+    }
 }
 
+
```
Comment (Peefy) [inline kclvm/sema/src/resolver/doc.rs:25]: cargo fmt check CI failed. @He1pa

**Review by Peefy — APPROVED** [review]
LGTM

**Review by Peefy — APPROVED** [review]
Good Job! LGTM
