### PR TITLE
fix: fix completion when schema end pos is eof

### LINKED ISSUE #1099: [Enhancement] When the end of the schema statement is an eof token, the check expression does not trigger completion.
When the end of the schema statement is an eof token, the check expression does not trigger completion.

```python
schema Name:
    name: str
    check:
          <cursor> # Note that this is an EOF token instead of a newline token.
```

The expected completion list should include the attribute `name`.

### PR DESCRIPTION
**Pull request by He1pa**
Insert a fake new line character to expand the scope of the schema, used to complete the schema attributes at the end of the file

#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y

fix #1099

#### 2. What is the scope of this PR (e.g. component or file name):
kclvm/parser/src/parser/stmt.rs

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [x] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

File: kclvm/parser/src/parser/stmt.rs [hunk 1]
```diff
@@ -737,7 +737,14 @@ impl<'a> Parser<'a> {
         if let TokenKind::Indent(VALID_SPACES_LENGTH) = self.token.kind {
             let body = self.parse_schema_body();
 
-            let pos = self.token_span_pos(token, self.prev_token);
+            let mut pos = self.token_span_pos(token, self.prev_token);
```
Comment (Peefy) [inline kclvm/parser/src/parser/stmt.rs:740]: CI and DCO failed. Besides, you can use `fix #1099` in the description of PR to automatically close the issue when the PR is merged.

**Review by Peefy — APPROVED** [review]
LGTM
