### PR TITLE
fix: relative path calculation is using the full path after symbolic link

### LINKED ISSUE #1660: bug: when the full path of a symbolic link is used as the compile entry, the compilation fails
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

The use case:

```
$ tree
.
├── aaa
│   ├── kcl.mod
│   ├── kcl.mod.lock
│   └── sub
│       ├── sub.k
│       └── main.k
└── bbb
    ├── sub.k -> /Users/ccc/aaa/sub/sub.k
    ├── kcl.mod
    ├── kcl.mod.lock
    └── main.k -> /Users/ccc/aaa/sub/main.k
```

The `sub.k`

```
sub = 1
```

The `main.k`

```
import .sub as s

The_first_kcl_program = 'Hello World!'
b = s.sub
```

Compile `main.k` under `bbb`

```
$ cd bbb
$ kcl run main.k
```

```
error[E2F04]: CannotFindModule
 --> /Users/ccc/bbb/main.k:1:1
  |
1 | import .sub as s
  | ^ Cannot find the module .sub from //bbb/sub
  |


suggestion: try 'kcl mod add ' to download the missing package


suggestion: browse more packages at 'https://artifacthub.io'


error[E2G22]: TypeError
 --> /Users/ccc/bbb/main.k:4:5
  |
4 | b = s.sub
  |     ^ attribute 'sub' not found in 'module '..bbb.sub''
  |
```

### 2. What did you expect to see? (Required)

The compile result

```
The_first_kcl_program: Hello World!
b: 1
```

### 3. What did you see instead (Required)

The error

```
error[E2F04]: CannotFindModule
 --> /Users/ccc/bbb/main.k:1:1
  |
1 | import .sub as s
  | ^ Cannot find the module .sub from //bbb/sub
  |


suggestion: try 'kcl mod add ' to download the missing package


suggestion: browse more packages at 'https://artifacthub.io'


error[E2G22]: TypeError
 --> /Users/ccc/bbb/main.k:4:5
  |
4 | b = s.sub
  |     ^ attribute 'sub' not found in 'module '..bbb.sub''
  |
```

### 4. What is your KCL components version? (Required)

The main branch of `kpm`, `kcl` and `kcl cli`.

### PR DESCRIPTION
**Pull request by zong-zhe**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y

closes #1660  

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [x] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

File: kclvm/config/src/vfs.rs [hunk 1]
```diff
@@ -38,6 +41,20 @@ pub fn fix_import_path(root: &str, filepath: &str, import_path: &str) -> String
     // abspath: import path.to.sub
     // fix_import_path(root, "path/to/app/file.k", "path.to.sub") => path.to.sub
 
+    // Use canonicalize to convert the path to absolute path
+    // avoid the symbolic link issue caused the file not found
+    let filepath = fs::canonicalize(filepath)
```
Comment (He1pa) [inline kclvm/config/src/vfs.rs:46]: Is need `adjust_canonicalize()`  to handle Windows drive letter prefixes?

Comment (zong-zhe) [reply kclvm/config/src/vfs.rs]: fixed
