### PR TITLE
Fix net spit and join functions

### LINKED ISSUE #1899: net.join_host_port mishandles IPv6 address literals
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```kcl
import net
assert net.join_host_port("2001:DB8::", "80") == '[2001:DB8::]:80'
```

### 2. What did you expect to see? (Required)

Assertion passes

### 3. What did you see instead (Required)

`assert net.join_host_port("2001:DB8::", "80")` returns the incorrect value `'2001:DB8:::80'

### 4. What is your KCL components version? (Required)

Whatever https://play.kcl-lang.io/ is running.

### PR DESCRIPTION
**Pull request by johngmyers**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 

fix #1899

#### 2. What is the scope of this PR (e.g. component or file name):

kclvm/runtime/src/net

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Other

If `None`passed in arguments, returns `None`.
Fixes the handling of IPv6 address literals.
Adds more input validation.

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

...Modulo bug-dependency.

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [x] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

File: kclvm/runtime/src/net/mod.rs [hunk 1]
```diff
@@ -19,12 +19,78 @@ pub extern "C-unwind" fn kclvm_net_split_host_port(
     let kwargs = ptr_as_ref(kwargs);
     let ctx = mut_ptr_as_ref(ctx);
 
-    if let Some(string) = get_call_arg_str(args, kwargs, 0, Some("ip_end_point")) {
-        let mut list = ValueRef::list(None);
-        for s in string.split(':') {
-            list.list_append(&ValueRef::str(s));
+    if let Some(ip_end_point) = get_call_arg(args, kwargs, 0, Some("ip_end_point")) {
```
Comment (He1pa) [inline kclvm/runtime/src/net/mod.rs:22]: can we use std::net?
https://doc.rust-lang.org/std/net/enum.SocketAddr.html

Comment (johngmyers) [reply kclvm/runtime/src/net/mod.rs:22]: `SocketAddr::parse_ascii` is listed as unstable. It also doesn't handle domain names, which this function needs to.

**Review by He1pa — APPROVED** [review]
lgtm

**Review by zong-zhe — APPROVED** [review]
LGTM
