### PR TITLE
Fix goto attr def from attr def itself, add test cases on goto-def and find-refs

### LINKED ISSUE #754: [Bug fix] find reference on schema attribute failed

### PR DESCRIPTION
**Pull request by amyXia1994**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [X] Y 

close #754
It turns out the the find refs failed from the schema attribute def, is caused because the goto-def ignored the case when goto-def from schema attr def. Thanks to @He1pa we fixed the bug and added more tests on it.

#### 2. What is the scope of this PR (e.g. component or file name):

- the fix: 
  - kclvm/tools/src/LSP/src/util.rs
- the tests:
  - kclvm/tools/src/LSP/src/find_refs.rs
  - kclvm/tools/src/LSP/src/goto_def.rs

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):
Fix goto attr def from attr def itself, add test cases on goto-def and find-refs

- [X] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [X] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [X] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

File: kclvm/tools/src/LSP/src/find_refs.rs [hunk 1]
```diff
@@ -209,4 +209,56 @@ mod tests {
...
+                        logger,
+                    ),
+                );
+            }
+            Err(_) => assert!(false, "file not found"),
+        }
+    }
+
+    #[test]
+    fn find_refs_from_none_kpm_package() {
```
Comment (Peefy) [inline kclvm/tools/src/LSP/src/find_refs.rs:261]: Remove un-used code or add test cases.

Comment (amyXia1994) [reply kclvm/tools/src/LSP/src/find_refs.rs:258]: sorry done fixed

**Review by Peefy — APPROVED** [review]
LGTM
