### PR TITLE
fix: formatting support for multiple if statements

### LINKED ISSUE #1039: kcl fmt command removes legit code when formatting
### 1. Minimal reproduce step

When using kcl fmt command on the following file, it removes a whole part of its source code and does not just reformat it:
```
computeItems = lambda a: [str], b: [str], c: [str], item_nb: str -> [str] {
  if (a is Undefined) and (b is Undefined) and (c is Undefined):
    _r: [str] = ["a b and c are undefined"]
  else:
    if a is Undefined:
      a = ["default a value"]
    if b is Undefined:
      b = ["default b value"]
    if c is Undefined:
      c = []
    _r = c + a + b
  _r
}
```

The result I got from the `kcl fmt` command is:
```
computeItems = lambda a: [str], b: [str], c: [str], item_nb: str -> [str] {
    if (a is Undefined) and (b is Undefined) and (c is Undefined):
        _r: [str] = ["a b and c are undefined"]
    elif a is Undefined:
        a = ["default a value"]

    _r
}
```

It looks like every sub statement branches are erased except the first one.
For context, the lambda is used in a Mixin to handle cases where some optional fields are omitted.

### 2. What did you expect to see?

The code should not disappear, formatting the KCL code should be a safe operation.

### 3. What is your KCL components version?

Tested on the latest 0.7.5 version, but I was able to reproduce on older versions (0.6.x).

### PR DESCRIPTION
**Pull request by shashank-iitbhu**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references:

- [ ] N
- [x] Y 

fixes #1039 

#### 2. What is the scope of this PR (e.g. component or file name):

```kclvm/ast_pretty/src/node.rs```

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

https://github.com/kcl-lang/kcl/assets/134289475/b70dd7d7-c932-4761-8857-81b2e25c0966

- Since `if_stmt.orelse` is `Vec<NodeRef<Stmt>>`, so to format the code correctly for multiple if statements inside an else block, had to iterate through all the elements of `if_stmt.orelse`.
- This approach ensures that all the if statements are formatted correctly.

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

**Comment by shashank-iitbhu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by shashank-iitbhu** [comment]
recheck

**Comment by shashank-iitbhu** [comment]
@Peefy Any idea why these workflows are failing? went through the logs, I think these workflows need to be updated.

File: kclvm/ast_pretty/src/node.rs [hunk 1]
```diff
@@ -122,22 +122,20 @@ impl<'p, 'ctx> MutSelfTypedResultWalker<'ctx> for Printer<'p> {
         self.stmts(&if_stmt.body);
         self.write_indentation(Indentation::Dedent);
         if !if_stmt.orelse.is_empty() {
-            if let ast::Stmt::If(elif_stmt) = &if_stmt.orelse[0].node {
```
Comment (Peefy) [inline kclvm/ast_pretty/src/node.rs:125]: I think the current code modification is incorrect, which resulted in the test not passing. I suggest adding unit testing for any modifications. https://github.com/kcl-lang/kcl/blob/main/kclvm/ast_pretty/src/tests.rs

I think the correct way to fix this issue is to perform pattern matching on orelse, printing elif only when orelse has and only has one if stmt statement, and in other cases, it is a list of else statements

```rust
if if_stmt.orelse.len() == 1 {
    if let ast::Stmt::If(elif_stmt) = &if_stmt.orelse[0].node {
                      // Nested if statements need to be considered,
                // so `el` needs to be preceded by the current indentation.
                self.fill("el");
                self.walk_if_stmt(elif_stmt);
   } else {
                       // Nested if statements need to be considered,
                // so `el` needs to be preceded by the current indentation.
                self.fill("else:");
                self.write_newline_without_fill();
        ...
   }
} else {
                   // Nested if statements need to be considered,
                // so `el` needs to be preceded by the current indentation.
                self.fill("else:");
                self.write_newline_without_fill();
   ...
}
```

Comment (shashank-iitbhu) [reply kclvm/ast_pretty/src/node.rs:125]: Hey! fixed this in the latest commit, all the tests are passing now. I realised later that my fix was formatting each `if` stmt to have an `elif` stmt, my bad.
