### PR TITLE
fix: literal str and join str inner completion

### LINKED ISSUE #1083: [Bug] Wrong dot completion for the internal interpolation content of string
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
s = "hello ${."
```

### 2. What did you expect to see? (Required)

No completion of str member function.

### 3. What did you see instead (Required)

image

### 4. What is your KCL components version? (Required)

KCL v0.8.0-alpha.1

### PR DESCRIPTION
**Pull request by He1pa**
Remove the special judgment for literal strings during completion, and change the search for the nearest symbol during completion to the symbol one or two characters before the trigger.

#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y

fix #1083  

#### 2. What is the scope of this PR (e.g. component or file name):
kclvm/tools/src/LSP/src/completion.rs

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [x] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

File: kclvm/tools/src/LSP/src/completion.rs [hunk 1]
```diff
@@ -225,51 +225,21 @@ fn completion_dot(
...
+            return completion_import(&stmt, &pre_pos, program);
         }
     }
 
     // look_up_exact_symbol
     let mut def = find_def_with_gs(&pre_pos, gs, true);
     if def.is_none() {
-        // look_up_closest_symbol
-        def = find_def_with_gs(pos, gs, false);
+        // handel `symbol?.`
```
Comment (Peefy) [inline kclvm/tools/src/LSP/src/completion.rs:236]: s/handel/handle

File: kclvm/tools/src/LSP/src/completion.rs [hunk 2]
```diff
@@ -225,51 +225,21 @@ fn completion_dot(
     };
 
     if let Some(stmt) = program.pos_to_stmt(&pre_pos) {
-        match stmt.node {
```
Comment (Peefy) [inline kclvm/tools/src/LSP/src/completion.rs:228]: CI failed.

File: kclvm/tools/src/LSP/src/completion.rs [hunk 3]
```diff
@@ -225,51 +225,21 @@ fn completion_dot(
...
     // look_up_exact_symbol
     let mut def = find_def_with_gs(&pre_pos, gs, true);
     if def.is_none() {
-        // look_up_closest_symbol
-        def = find_def_with_gs(pos, gs, false);
+        // handel `symbol?.`
+        let pre_pos = KCLPos {
+            filename: pos.filename.clone(),
+            line: pos.line,
+            column: pos.column.map(|c| c - 2),
```
Comment (Peefy) [inline kclvm/tools/src/LSP/src/completion.rs:240]: What does `- 2` mean here? Could you pls add more comments here?

Consider the following code

```python
a = "1"?  .capitalize()  # The width of `?  .` is not `2`.
```

File: kclvm/plugin/build/lib.macosx-11-arm64-cpython-39/kclvm_runtime.py [hunk 4]
```diff
@@ -0,0 +1,99 @@
+# Copyright 2021 The KCL Authors. All rights reserved.
```
Comment (Peefy) [inline kclvm/plugin/build/lib.macosx-11-arm64-cpython-39/kclvm_runtime.py:1]: Remove unused files.
